name: Lint & Tests

on: [pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install swiftlint 
        run: brew install swiftlint || brew upgrade swiftlint 
      - name: Run linting
        run: swiftlint lint --strict
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      # - name: List XCode Schemes
      #   run: xcrun xcodebuild -list
      # - name: Install Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.0'
      #     bundler-cache: true
      - name: Run Tests
        run: bundle exec fastlane scan
