name: Lint & Tests

on: [pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install swiftlint 

        run: brew install swiftlint || brew upgrade swiftlint 

      - name: Run linting
        run: swiftlint lint --strict

  test:
    runs-on: macos-14
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15"
      
      - name: Get XCode schemes 
        run: xcrun xcodebuild -list

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Run tests 
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'scan'