name: Lint & Tests

on: [pull_request]

jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Install swiftlint 
        run: brew install swiftlint || brew upgrade swiftlint 

      - name: Run linting
        run: swiftlint lint --strict

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0' 

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install cocoapods
        run: gem install cocoapods


  test:
    runs-on: macos-14
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2.0"
      
      - name: Get XCode schemes 
        run: xcrun xcodebuild -list

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install cocoapods
        run: gem install cocoapods

      # - name: Run linting OrttoSDKCore
      #   run: pod lib lint OrttoSDKCore.podspec --allow-warnings --swift-version=5.10 --verbose
      # - name: Run linting OrttoPushMessaging
      #   run: pod lib lint OrttoPushMessaging.podspec --allow-warnings --swift-version=5.10 --verbose
      # - name: Run linting OrttoPushMessagingFCM
      #   run: pod lib lint OrttoPushMessagingFCM.podspec --allow-warnings --swift-version=5.10 --verbose
      # - name: Run linting OrttoPushMessagingAPNS
      #   run: pod lib lint OrttoPushMessagingAPNS.podspec --allow-warnings --swift-version=5.10 --verbose
      # - name: Run linting OrttoInAppNotifications
      #   run: pod lib lint OrttoInAppNotifications.podspec --allow-warnings --swift-version=5.10 --verbose
      
      - name: Run tests 
        run: bundle exec fastlane scan --verbose